### ISSUE TITLE
How to solve the CUDA error of invalid device function?

### ISSUE THREAD

**Issue by ShunLu91** [1ytic/pytorch-edit-distance#12]
I use this function in PyTorch 1.7.0 with cuda=10.2, and this error troubles me. 
I have tried .cuda() or torch.device('cuda:0'), which are both useless.
Could you please help me solve it?

```python
Traceback (most recent call last):
  File "train_supernet_spos.py", line 55, in <module>
    main()
  File "train_supernet_spos.py", line 51, in main
    trainer.train(model, epochs=args.epochs, lr=args.lr, reset=args.reset, model_name=args.exp_name)
  File "/home/lushun/code/nas-lib-map/source_repos/nb-asr-main/nasbench_asr/training/torch/trainer_spos.py", line 169, in train
    per = self.decode(logits, logits_len, val_input)
  File "/home/lushun/code/nas-lib-map/source_repos/nb-asr-main/nasbench_asr/training/torch/trainer_spos.py", line 271, in decode
    per = ed.compute_wer(top_beams, targets, top_beams_len, targets_len, blank, sep)
  File "/home/lushun/anaconda3/envs/pt1.7.0/lib/python3.7/site-packages/torch_edit_distance/__init__.py", line 97, in compute_wer
    data = levenshtein_distance(hs, rs, hn, rn, blank, space).float()
RuntimeError: CUDA error: invalid device function
```

**Comment by 1ytic** [comment]
You can try updated version `torch_edit_distance==0.4.0`. Make sure the package is installed on the same machine/environment where it will be used.

**Comment by ShunLu91** [comment]
Thanks for updating the code. I have tested the suggested version 0.4.0 and it works.
Best wishes.
